### ISSUE TITLE
Incompatibilities due to new openai-whisper version

### ISSUE THREAD

**Issue by JaMeZ-B** [ManimCommunity/manim-voiceover#55]
#### Preliminaries

- [x] I have followed the latest version of the
      [installation instructions](https://github.com/ManimCommunity/manim-voiceover/blob/main/README.md).

## Description of error
I believe that it has become impossible to use transcripition with `openai-whisper` on macOS (and presumably Windows) in the latest version of `manim-voiceover`. 

Let me explain: Recently the transcription module was updated to be compatible with `openai-whisper>20230306`. This whisper version adds a dependency on openai's `triton`, which unfortunately has only `manylinux` wheels, as you can see [here](https://pypi.org/project/triton/#files). Hence, on non-Linux machines manually building triton (in version `>=2.0.0`) is the only option to get the transcription part of `manim-voiceover` to work.

To me personally this means, that I will stick to the Azure service or even use two different python environments (I wanted to use GTTS for early versions of my next video because its free).

## Installation logs

<details><summary>Terminal output</summary>

poetry error when setting up the environment:
```
Unable to find installation candidates for triton (2.0.0.post1)
```

</details>

## System specifications

<details><summary>System Details</summary>

- OS: macoS 13.3.1 
- RAM: 64 GB
- Python version (`python/py/python3 --version`): 3.11
</details>

<details><summary>LaTeX details</summary>

+ LaTeX distribution (e.g. TeX Live 2020):
+ Installed LaTeX packages:

</details>

<details><summary>FFMPEG</summary>

Output of `ffmpeg -version`:

```
PASTE HERE
```
</details>

**Comment by osolmaz** [comment]
Are you on Mac M1 or intel? I am also on M1 with MacOS 13.3, and I did not issue anything with triton.

Also, can you maybe try with Python 3.10 and let me know if that changes anything?

**Comment by JaMeZ-B** [comment]
I just tried it on an Intel mac with python 3.10.11 and the following `pyproject.toml`:

```toml
[tool.poetry]
name = "manim-test"
version = "0.1.0"
description = ""
authors = ["Jannes Bantje <j.bantje@wwu.de>"]
readme = "README.md"
packages = [{include = "manim_test"}]

[tool.poetry.dependencies]
python = "3.10.11"
manim = "^0.17"
manim-voiceover = { version = "^0.3.3", extras = ["all"] }


[tool.poetry.group.dev.dependencies]
ipython = "*"
ipykernel = "*"
setuptools = "*"
wheel = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

sadly the triton dependency still causes `Unable to find installation candidates for triton (2.0.0)`

I will try it on my M1 mac later.
